// Header photo for each page, as on the old site (generated by scripts/prep-heroes.mjs).
const keys = new Set([
  'la-storia', 'il-consiglio', 'il-nodo', 'unisciti-a-noi', 'alpinismo', 'contatti', 'roccia',
  'alpinismo-giovanile', 'arrampicata', 'corsa-in-montagna', 'corsi', 'escursionismo', 'cultura',
  'eventi-sociali', 'sci-alpino', 'sci-fondo',
]);

// Sections without their own photo on the old site.
const aliases: Record<string, string> = {
  attivita: 'alpinismo',
  calendario: 'escursionismo',
  'lo-statuto': 'la-storia',
};

export function heroImage(key: string) {
  const k = keys.has(key) ? key : (aliases[key] ?? 'roccia');
  return `/media/site/testate/${k}.webp`;
}
